name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Build & Test
        run: |
          set -o pipefail
          xcodebuild \
            -project GaitCoach.xcodeproj \
            -scheme "GaitCoach" \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro' \
            -configuration Debug \
            -testPlan "GaitCoachTests" \
            clean test
