name: iOS CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build & Test
        run: |
          set -eo pipefail
          xcodebuild \
            -project GaitCoach.xcodeproj \
            -scheme "GaitCoach" \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro' \
            -configuration Debug \
            clean test
