name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode 15.4
        run: sudo xcode-select -switch /Applications/Xcode_15.4.app

      # (optional) tiny sanity check so we can see the project in logs next time
      - name: List repo contents
        run: ls -la

      - name: Build & test
        run: |
          set -euo pipefail
          # show what xcodebuild sees (useful if it ever fails again)
          xcodebuild -list -project GaitCoach.xcodeproj
          # build + run tests
          xcodebuild \
            -project GaitCoach.xcodeproj \
            -scheme GaitCoach \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro' \
            clean test
          # If you want to force a specific test plan, add:
          #   -testPlan Unit
          # (or whatever your plan is actually named)
